### ISSUE TITLE
#0011 Proof-of-Stake inflation adjustment

### ISSUE THREAD

**Issue by peerchemist** [peercoin/rfcs#19]
While PoS inflation can currently be up to 1% per year, in reality only a fraction of the existing coins participate in the minting process. This RFC will seek to continuously adjust the PoS block reward such that PoS inflation approximates to 1%/year on average, no matter how much PoS participation there is. In general, this RFC will look into the intricacies of tying a block reward to the total supply, as well as how to safely implement a fluctuating block reward.

https://github.com/peercoin/rfcs/blob/master/text/0011-pos-inflation-adjustment/0011-pos-inflation-adjustment.md

**Comment by Rakete4** [comment]
Be very careful with such a dynamic PoS reward algorithm! It can lead to oscillation cycles.

If some minters halt minting for speculative reasons, i.e. when they expect the reward to increase, they are producing a self-fulfilling prophecy, as their behaviour in fact increases the reward. When the expected top of the minting reward is reached, they will resume minting. If a significant number of minters behave like that, minting participation will be negatively impacted. The situation can exacerbate by itself, as honest minters would be punished by receiving lower average rewards. 
It can lead to oscillation, particularly because minters who miss out on a reward peak can again halt minting and resume minting on the next peak. Since we do not have a maximum reward, they will only miss out on a negligible compound interest.

In the end, the blockchain could be less secure because minting participation could temporarily drop to a lower level than where it is now. And we would pay for less security with higher inflation, a lose-lose situation!

Decred had such a problem of oscillation in their ticket prices, because of wrong incentives that resulted from a poor algorithm.
https://dcrstats.com/
Scroll down to POS ticket price and select "All time". Then you see the oscillation until mid 2017.

Ötzi from Peercointalk.

**Comment by Nagalim** [comment]
Seasonal timing attacks have now been recognized in the rfc, and a recursive calculation added to punish very very large one-block minters.  Ultimately, this proposal is extremely unlikely to cause less participation than we have now because we are currently below the minimum participation threshold of 20%, such that this proposal will act as simply a 5x increase in block reward in the short term.  No timing attacks are possible while we operate below the 20% threshold, as the reward would be at a maximum right now and there is no logical reason to wait.
