### ISSUE TITLE
#0003 Multi-signature Minting

### ISSUE THREAD

**Issue by hrobeers** [peercoin/rfcs#4]
To be discussed.

**Comment by youngpascal** [comment]
[RFC #0003](https://github.com/peercoin/rfcs/blob/master/text/0003-multisig-minting/0003-multisig-minting.md)

**Comment by d5000** [comment]
Support from my side (non-developer perspective, so I don't fully know the technical details), the rationale seams reasonable and I consider the cold-minting feature very important.

**Comment by Cybnate** [comment]
Bit on the fence with this one. Disadvantage is loosing a number of peers even though they are intermittent when people only mint occasionally. 
The minting reward is to secure the network what is left of that with cold minting? Do the risks of users weigh up against the risks of the network?

**Comment by nohea** [comment]
This is like the holy grail of proof-of-stake: trustless minting/staking of coins without having your keys on a hot server. 
There are still minting nodes issuing blocks and securing the network. It's just that you don't need your spending key on the hot node to do it.

**Comment by hrobeers** [comment]
@Cybnate the users only risk losing the reward, not their stake.
Users will still be able to mint from and to P2PKH adresses and can also just mint there own multisig adresses.

Outsoursing minting is not the main goal of this RFC, the main goal is to be able to mint funds secured by offline keys (2-3 multisig with only one hot key).

**Comment by sigmike** [comment]
This is listed as an advantage:

> Permanent outsourcing of minting is not possible, every mint needs to be pre-signed by the holder.

But I see it mostly as a drawback. Minters who want cold minting don't want to load their cold wallet to continue minting when the pre-signed transaction is used.
The minter can probably prepare a lot of chained CoinStake transactions from the cold wallet so that he can mint for many years. Is this how cold minting is intended to work in this proposal?
He will also have to do that each time new coins are sent to his cold wallet.

**Comment by Nagalim** [comment]
The actualy proposal is simply to allow the coinstake and the coinbase to be signed by different multisig keys.  There are no attacks on the broader chain that I can think of here, so analysis is really only limited to the technicalities of an individual using this as intended.  If we build the infrastructure, I dont think this rfc introduces vulnerabilities.  It does add complexity, however the original single-sig can be done so the complexity is only optional.

A good perspective on this proposal is that we will already have cold minting from rfc0002.  Minters can sign txns offine once a month and move the signed txns online such that the actual wallet never needs to touch a live machine.  This proposal simply allows the hot-machine that the minter sends the presigned txns to to be owned by someone else.  So my point here is that while someone who doesn't care about hot and cold would see the periodic signature thing as an inconvenience (like sigmike says), a cold-minter would love it.  Essentially we are forcing those who use multisig to also cold-mint (or some semblance thereof).  This is not the worst thing in the world; while it is not infinitely convenient, I see it as putting in mandatory checks to prevent someone from gaining permanent access over your power to mint.  It's sacrificing convenience for security.

**Comment by hrobeers** [comment]
> A good perspective on this proposal is that we will already have cold minting from rfc0002.

@Nagalim this is not true, only multisig minting enables some form of cold minting. Upon block creation, a signature is required to sign the block, so a single key address would still require the key to be online.

> He will also have to do that each time new coins are sent to his cold wallet.

@sigmike no he does not have to, he only has to do that when he wants the new UTXOs to mint. The old ones will still be able to mint without interaction.

This proposal allows the minter to pre-sign minting transactions off-line.

I consider permanent outsourcing a risk as it would break down the democratic principle of one coin one vote. Minting pools could become extremely powerful when they would be given indefinite power over sleeping coins.

However, the most important use of this proposal is not outsourcing minting, but rather being able to mint multisig addresses with only one key online even when multiple are required to sign transactions.

**Comment by sigmike** [comment]
I'm not sure this is what the community expects when we say cold minting. They would have to regularly load their cold storage wallet on a computer and do some transfers to their hot wallet to continue minting. 
This is probably a discussion to have with the community first.

**Comment by peerchemist** [comment]
The RFC is called "Multi-signature Minting". It sure is not cold minting as people usually expect it but it opens another path toward that. There is no confusion about it in my opinion.

**Comment by hrobeers** [comment]
This RFC does not claim to implement cold minting, the community concluded this is similar in some way.

The only reference to cold minting in the RFC:
> In combination with mutli-signature scripts, this could serve as an alternative to cold minting.

Community should definitely understand this as much as possible, unfortunately like with any technical debate community tends to oversimplify and even misinterpret the facts.

The debate whether this is `cold minting` or not should be held outside of this proposal.

**Comment by Nagalim** [comment]
Hrobeers is right about this rfc being needed for this functionality, because otherwise you'd have to sign the coinstake and the coinbase with the same private key.

My interpretation of 'cold minting' is that of being able to sign the transaction offline, move the signed transaction to a hot node (via for example an intermediary external drive with a hardware switch) and mint when the time comes.  By that definition, the frequency with which you have to use the cold wallet to sign things is not a factor, instead it is the device access to the internet which matters.  By that definition, this rfc accomplishes cold minting.

I think it is important to understand what concrete benefits these rfcs provide.  While you may consider 'cold minting' to simply be a social construct and not reflective on the actual development, no one has ever accomplished 'cold minting' before.  If we implement this innovation we should claim the title because it doesn't exist otherwise.  It also gestures to a potential future where minters only have to access their coins once every thirty days in order to be continuously minting through a pool.  This could greatly increase participation in the network, and therefore could possibly have an even stronger effect than the benefits it gives to traditional multisig addresses.  As such, I think it is an important aspect of this proposal, and references a real benefit to the network no matter what name we give it.  That said, we should totally call it 'cold minting', even though it may require accessing the wallet every thirty days.

**Comment by sigmike** [comment]
Is there really a demand for this? I'm not convinced people would actually use it. That's the topic I meant when I suggested a community discussion, whatever the name of the solution.

The RFC says it "requires minimal changes to the protocol, provided that RFC-0002 and RFC-0004 are implemented", but RFC-0002 is certainly not a small change. And since RFC-0002's other motivation [is not needed](https://github.com/peercoin/rfcs/issues/3#issuecomment-390471659), its sole purpose is the implementation of RFC-0003. So this RFC actually requires important changes that should be considered only if it's really useful.

> no one has ever accomplished 'cold minting' before

I made an implementation in https://github.com/peercoin/peercoin/pull/78.

**Comment by peerchemist** [comment]
> Is there really a demand for this? I'm not convinced people would actually use it.

Absolutely, multisig minting and minting pools is a must for the future of the Peercoin. People will use it if given the proper tools to handle the process.

**Comment by peerchemist** [comment]
@sigmike this still leaves a way for the >actual cold< minting as described in your proposal or some other solution which is yet to be proposed.

**Comment by sigmike** [comment]
I think the benefits of this RFC are not worth the effort and complexity increase (most of the complexity comes from the required RFC 2 which would be implemented only for this RFC).

I think this effort would be better spent in a true cold minting implementation that enables minting without having to bring the private keys online regularly.

**Comment by sigmike** [comment]
Actually I think multisig minting is already possible without this RFC.

The public key used to verify the block signature is the key of the second *output* of the CoinStake, not its input[[1]](https://github.com/peercoin/peercoin/blob/d243de6db10694d436b96b140257e7a20e47e61f/src/main.cpp#L2777).

So we should be able to make a block from a multisig output. The only restriction should be that second output of the CoinStake must be a pay-to-pubkey script, and this pubkey will be used to verify the block signature.

So this second output cannot send coins back to the multisig, but its value can include only the reward, or even be zero. Another output can send the remaining value back to the multisig address.

**Comment by Nagalim** [comment]
That sounds like we can start implementing minting pools right now, all we have to do is make a good user interface.  A user can make a 2-of-3 multisig address, form a coinstake txn with an output to an address corresponding to one of the 2 remaining multisig keys and sign once, then give the txn along with that key to a pool operator.  The pool can then mint and socialize the rewards, using that key to signature the block.  Is that correct?

**Comment by sigmike** [comment]
Yes, but since there's still the timestamp in the transaction, the partially signed CoinStake must also have a time that will (most likely) make it a valid proof of stake. I think there are programs to find that time.

It would be interesting to verify all that on testnet.

**Comment by Nagalim** [comment]
If rfc0004 is all that is needed to introduce minting pools, that is a wonderful revelation.

**Comment by hrobeers** [comment]
Great insight @sigmike !
I agree that it should be used first to see whether these RFCs would provide value.
