### ISSUE TITLE
#0004 Remove Transaction Timestamp

### ISSUE THREAD

**Issue by hrobeers** [peercoin/rfcs#5]
To be discussed.

**Comment by Nagalim** [comment]
It has been some time since this RFC has been proposed and discussed by the community, so I just want to speak to why this RFC is so elegant to me.  Not only does it allow for some foreseen technical benefits, it also changes some of the underlying philsophy of Peercoin.  The structure of Peercoin currently has a number of redundancies caused by adapting the underlying PoW-focused block structure of BTC, and when you dive into the construct it ends up looking something like a Frankenstein at times.  By engineering away the redundancies with purpose, we fill out the space and give order and meaning where there once was arbitrary redundancy (that could be taken advantage of for nefarious purposes).

All together, I think this RFC is a huge step in the right direction with a low effort.  While the tangible immediate benefits may be sparse, the restructuring represents far more than that, even without the other benefits outlined by other RFCs.

**Comment by peerchemist** [comment]
I agree with @Nagalim, this proposal is major step forward for Peercoin.

**Comment by youngpascal** [comment]
[RFC #0004](https://github.com/peercoin/rfcs/blob/master/text/0004-remove-transaction-timestamp/0004-remove-transaction-timestamp.md)

I can't see a possible problem with removing the Transaction Timestamp long term. As @Nagalim pointed out, the very core of software engineering aims to remove all redundancy in a perfect world. The benefits of reducing block size may not matter now, but looking into the future and taking a page from Bitcoin's book, any effortless reduction of block size now can have monumental impacts down the road.

**Comment by backpacker69** [comment]
It is redundant to have timestamp in transaction, I agree, it would be great if we didn't have it.

However, after so many years, every piece of software we rely on for infrastructure  knows about it and will break if we remove timestamp from transaction. Some of the issues will be mitigated by continued inclusion in transaction data of rpc methods, but any software that does serialisation/deserialisation of transactions will not be able to handle absence of timestamp field. 

And while there's definitely a lot of blockchain related software out there that does not know about timestamp in transactions, changes required to add timestamp to such projects are relatively small compared to the whole task of making it work with peercoin.

My short take on the matter, wasting time on fixing all existing infrastructure in distant hope that more software will be adapted to work on peercoin is futile. You could spend same time on adaptation projects alone and have more compatible software at the end.

**Comment by hrobeers** [comment]
For the RPC interface, I'd still include the transaction timestamp by default (taking the block timestamp), for the JSON-RPC this shouldn't matter for compatibility. For the RAW transaction interface, I'd include a startup parameter that discards the timestamp for compatibility with bitcoin software.

**Comment by d5000** [comment]
Support from my side (non-developer perspective, so I don't fully know the technical details), the rationale seams reasonable and I consider the cold-minting feature very important.

**Comment by nohea** [comment]
It's redundant. Drop it. It's good to stick close to Bitcoin, except where Peercoin explicitly innovates. This is not one of those cases. 

I've been working on and off trying to port wallet software from Bitcoin to Peercoin, and this tx.timestamp doesn't even fit in. More noise.

**Comment by peerchemist** [comment]
Accepted. Details of implementation are yet to be defined.

**Comment by sigmike** [comment]
A drawback that is not mentioned is that all existing tools that already handle this timestamp (in raw transactions) will have to be updated. And new tools adapted from bitcoin ecosystem will still have to be updated to change the transaction version.

Also, if Bitcoin ever changes its version number to the same version as us, we will certainly not be compatible.

We may need a transition time where both transaction formats are accepted, to give people some time to upgrade their tools.

I said in another discussion that I wanted to check wether the timestamp is required somewhere where we don't have a block to get the time from. I did and I could not find any.

So I'm in favor of the RFC.

**Comment by hrobeers** [comment]
I came across a possible issue that unfortunately did not came out of the review process yet.
To me this issue seems to be the legitimation for the existance of the timestamp.

Peercoin transactions are not allowed to have a timestamp prior to the coins they spend.
Which is logical, since they are required to burn coindays (or at least keep them equal).
Blocks are not required to have increasing timestamps to allow clockdrift between miners and minters.
Therefore, transactions spending recently transacted coins might get delayed for inclusion in blocks if their previous block has a timestamp higher than the median block time. They will pend in the mempool until a block is mined with a timestamp higher than the previous transaction's block.

I believe both transaction version will need to keep coexisting in order to not limit the transaction usability, where the old transaction format will remain the default while the new transaction format can be optionally used to enable transactions created by bitcoin tools, like mining pools and transaction creating and signing applications.

This might complicate the ecosystem considerably so therefore I'd like to reopen this discussion.

**Comment by nohea** [comment]
Thanks for reopening the issue. 
I still need to process this fully but i have a couple reactions.
Supporting 2 tx formats does seem excessively complicated. 
If the txs spending recently transacted outputs need to wait for an extra block or three due to time drift and out of order block (now tx) timestamp, that doesn't seem such a big deal to me.

**Comment by peerchemist** [comment]
> This might complicate the ecosystem considerably so therefore I'd like to reopen this discussion.

I agree, and learning this now I am thinking to stop pursuing this RFC.

> They will pend in the mempool until a block is mined with a timestamp higher than the previous transaction's block.

This will hurt user experience a lot. It becomes clear that minting transactions should be separated from normal monetary transactions.

**Comment by Nagalim** [comment]
I don't think this is a big hit to user experience.  It would only affect those trying to transact a chain of transactions in several sequential blocks.  That is a rare occurance in the current climate, and arguably not the purpose of the chain in general.  Transacting every block is like the blockchain form of high frequency, which we have said we dont really need to support.

**Comment by hrobeers** [comment]
The is extra complexity can easily be hidden for the user (either GUI or RPC).
The transaction version does not need to be incremented in the classic way (+1), a bit flag could be set to indicate a transaction without timestamp, so both can keep coexisting even when a later fork increments the version number.
How I see a possible coexistence is in the ability to run the raw RPC interface in 'bitcoin compatibility mode' dropping the transaction timestamp in raw transactions. While in the default 'legacy mode', a dummy or block timestamp is serialized into the raw transaction. A 'raw mode' can be set to serialize the transactions as is.
This would allow mining software and bitcoin transaction signing software to be used by only setting the correct transaction version, without the need for adding timestamp logic, while still maintaining the timestamp for the majority of transactions.

Still the extra technical debt added to the node software cannot be neglected.

**Comment by peerchemist** [comment]
@hrobeers let's have a meeting and discuss this.

**Comment by sigmike** [comment]
> Peercoin transactions are not allowed to have a timestamp prior to the coins they spend.
Which is logical, since they are required to burn coindays (or at least keep them equal).

Can't we remove this restriction? If the maximum decrease is what is allowed in block time drift it doesn't seem to be an issue. And if an attacker does that repeatedly on his own chain the difficulty would increase way too much for this be be beneficial for anything.

> transactions spending recently transacted coins might get delayed for inclusion in blocks if their previous block has a timestamp higher than the median block time

Block times are usually in order. On a recent slice of 10k blocks there were only 136 blocks with a timestamp before the previous one. So this delay would be rare.

**Comment by Nagalim** [comment]
In discussing this proposal, we accumulated some additional insight.  First of all, it was discovered that multisig minting, air-gapped minting, and minting pools could already exist under the present protocol.  The following is a description of such:
1.  Use of the 'findstake' protocol can occur up to ~20 days in advance, revealing when a particular UTXO can mint.
2.  If this UTXO is located at a multisig address, the signers for this address could 'presign' the coinstake transaction well before the block is formed, therefore allowing multisig and air-gapped minting for a particular UTXO at a particular future timestamp.
3.  The presigned coinstake can be used by the designated public key owner to form a block at the allocated time.
This method does not introduce any additional attack vectors to the system and allows, e.g., mint pools to create blocks up to ~20 days after a particular stake window is found.  It also does not require rfc0004 in any way.  The primary consequence of rfc0004 on this method would be to remove the 'findstake' procedure from this method and allow the 'pool operator' to find a block at whatever window they choose.

Therein lies the attack vector that rfc0004 opens up: a 'pool operator' may delay the inclusion of the presigned coinstake into a block in order to time the signed coinstakes under their control into a 6-block string so as to force a re-org for the purposes of a double spend, or similar blockchain attack.  Under the current protocol this is impossible, as the multisig or air-gapped minters must select a specific time for their presigned UTXO that cannot be delayed.  Under rfc0004, the 'pool operator' is fully able to withhold a block creation in order to wait for a time when their other presigned mint stakes align for an attack.

This type of attack is prevalent in both rfc0004 and rfc0012, both of which give power to the 'pool operator', or designated multisig block creator, to decide when the signed coinstake transaction is used.  It is not present in the current protocol that contains a timestamp in the signed transaction because delays are untenable if they are timestamped in advance.

For these reasons, rfc0004 has the same (or similar) attack vector as rfc0012 (cold minting) and should be considered redundant in this aspect.  This leaves the only benefit of rfc0004 (to the exclusion of rfc0012) to be compatibility with current Bitcoin code while gaining the detriment of additional complexity in supporting multiple transaction formats.

Because the detriments are on par with the benefits, it is my suggestion that rfc0004 should be changed to a status of 'rejected'.
