### ISSUE TITLE
#0006 Remove Proof-of-Work Block Signature

### ISSUE THREAD

**Issue by hrobeers** [peercoin/rfcs#7]
To be discussed.

**Comment by youngpascal** [comment]
[RFC #0006](https://github.com/peercoin/rfcs/blob/master/text/0006-remove-pow-block-signature/0006-remove-pow-block-signature.md)

**Comment by backpacker69** [comment]
simplification of mining to cold storage will allow users to mine in more secure way. 

of course existing pool software would need to be modified to make use of that possibility. can we have input of pool operators on the matter?

**Comment by hrobeers** [comment]
You can already mine to cold storage as was illustrated by https://hrobeers.github.io/ppc-solo-mine/
Currently the block needs to be signed by only the first output, if you give 0 value, you can mine the full reward to cold storage.

The signature requirement should be removed mainly to remove the need to have wallet features enabled in the pool node.

I will add that to the RFC.

**Comment by peerchemist** [comment]
This is very important as it makes mining infrastructure compatible with the one of Bitcoin.

**Comment by backpacker69** [comment]
most of the mining infrastructure has peercoin implemented

**Comment by nohea** [comment]
Improving security and simplifying design is a good thing to do proactively, rather than retroactively. So that's a plus. 
Also, according to @hrobeers in a prior clarification, this will drop the PoW signature _requirement_ . But the blocks could still be signed. So maybe exisiting Peercoin mining pools wouldn't need to change anything if they don't want?

**Comment by hrobeers** [comment]
@nohea that is correct indeed, I'll add it to the RFC

**Comment by Nagalim** [comment]
This seems straightforward.  I would worry about the security implications, but because this complication was added by Peercoin for convenience, I trust Bitcoin's security here is fine.  Instead, I want to ask about future maintenance.  Sunny required this signature because it was convenient to do so in the code, correct?  From that perspective, how much future maintenance will this rfc generate when merging Bitcoin code in the future?

**Comment by peerchemist** [comment]
Implemented with v0.8~RC6.
